services:
  - type: web
    name: pharma-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GROQ_API_KEY
        sync: false
  - type: static
    name: pharma-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        sync: false